### PR TITLE
Feature/166 Add feedback forms

### PR DESCRIPTION
**Pull request by maxwowo**
This PR
- Adds a feedback button in the navbar which links to a Google form
- Changes "feedback" to "email" in the page footer
- Links Google form to about modal

image
image

### CODE REVIEW

**Comment by lukefisklennon** [comment]
I'd suggest perhaps putting the "feedback" to the right of the dark theme button, so all the text buttons are grouped together. What do you reckon?

**Comment by maxwowo** [comment]
> I'd suggest perhaps putting "feedback" to the right of the dark theme button, so all the text buttons are grouped together. What do you reckon?

Good point

**Comment by maxwowo** [comment]
> perhaps there could also be a link to the form over the "please contact us" in the About?

Fair enough

**Comment by esyw** [comment]
just noticed that on light mode, the feedback button text is black instead of white for me?

**Comment by maxwowo** [comment]
> just noticed that on light mode, the feedback button text is black instead of white for me?

Oops, good spot 💪

**Pull request merged**
