### PR TITLE
MUI v5

### PR DESCRIPTION
**Pull request by munjoonteo**

### CODE REVIEW

**Comment by martanman** [comment]
chrome_4mdcUy6mjA
Changing class button seems to trigger drag.

**Review by oliverxu42 — APPROVED** [review]
lgtm

**Comment by martanman** [comment]
weird blur on card on arrowicon mousedown and flashbang on mouseup
chrome_m5BwU4C7cP
h

**Review by martanman — APPROVED** [review]
lgtm I guess

**Pull request merged**
