### PR TITLE
add persuasive description

### PR DESCRIPTION
**Pull request by esyw**

### CODE REVIEW

**Comment by lukefisklennon** [comment]
What do you think of this:

> The best tool to plan your UNSW timetable with friends. Features coming soon include live share, auto timetabling, and more.

We would remove the "coming soon" once those features are done.

**Comment by maxwowo** [comment]
> What do you think of this:
> 
> > The best tool to plan your UNSW timetable with friends. Features coming soon include live share, auto timetabling, and more.
> 
> We would remove the "coming soon" once those features are done.

Sounds good

**Comment by esyw** [comment]
"The best tool to plan your weekly UNSW timetable with friends. Super easy, customizable drag and drop. Live share, auto timetabling, and more coming soon!"
maybe this to get more reference to current features? more SEO keywords lol? or maybe shorter better

**Comment by lukefisklennon** [comment]
> "The best tool to plan your weekly UNSW timetable with friends. Super easy, customizable drag and drop. Live share, auto timetabling, and more coming soon!"
> maybe this to get more reference to current features? more SEO keywords lol? or maybe shorter better

Yep ok, looks good 👍

**Review by lukefisklennon — APPROVED** [review]

**Review by maxwowo — APPROVED** [review]

**Pull request merged**
