### PR TITLE
Half-hour support

### PR DESCRIPTION
**Pull request by lukefisklennon**
Used ECON1101 for testing which has 90 minute lectures, as per [class util](http://classutil.unsw.edu.au/ECON_T1.html).

### CODE REVIEW

**Comment by maxwowo** [comment]
What are the changes in `package-lock.json` for?

**Comment by lukefisklennon** [comment]
@maxwowo btw I tried linting but it seemed to break things:
image

**Comment by maxwowo** [comment]
> 
> 
> @maxwowo btw I tried linting but it seemed to break things:
> image

Yep I fixed that issue earlier, it's to do with the linter incorrectly linting some of the default files. Don't worry about linting for this PR, I'll pull from dev in my PR and fix it up.

**Comment by lukefisklennon** [comment]
Alright cool

**Comment by lukefisklennon** [comment]
> What are the changes in `package-lock.json` for?

Oops didn't see this until now. It's something npm changes automatically when you run install, and apparently it's meant to be tracked by version control.

**Comment by maxwowo** [comment]
> 
> 
> > What are the changes in `package-lock.json` for?
> 
> Oops didn't see this until now. It's something npm changes automatically when you run install, and apparently it's meant to be tracked by version control. @maxwowo

Yeah I think it's changed by npm automatically, it's fine though since it didn't really break anything.

**Pull request merged**
